<?php

/**
 * PluginProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProfile');
    }
}