<?php

/**
 * PluginsfFacebookGraphUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfFacebookGraphUserProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfFacebookGraphUserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfFacebookGraphUserProfile');
    }
}