all:
  facebook:
    api_key: XXX
    app_secret: XXX
    app_id: XXX
    app_cookie: true
    app_cookie_domain: ~
    redirect_after_connect: false
    redirect_after_connect_url: ''
    connect_signin_url: 'sfFacebookConnectAuth/signin'
    app_url: '/my-app'
    guard_adapter: ~
    js_framework: jQuery # none, jQuery or prototype.

    # It is highly recommended to use a js framework if you want a correct experience in IE

  sf_guard_plugin:
    profile_class: sfGuardUserProfile
    profile_field_name: user_id
    profile_facebook_uid_name: facebook_uid # WARNING this column must be of type bigint ! 100000398093902 is a valid uid for example !
    profile_email_name: email
    profile_email_hash_name: email_hash
