default:
  facebook:
    api_key: XXX
    app_secret: XXX
    app_id: XXX
    app_cookie: true                  # whether to use cookies (needed to be true
                                      # as far as i'm aware)
    app_cookie_domain: ~
    connect_signin_url: 'sfFacebookGraphAuth/signin'
    redirect_on_no_session: true      # whether to perform a redirect (in
                                      # facebook js) when no session exists
    no_session_redirect_url: ~        # where to redirect to if there is no
                                      # facebook session will go through a
                                      # url_for (null is reload page)
    modify_sf_guard_user: true        # whether to alter sf_guard_user to not
                                      # have email address as required
    dont_store_proxy_emails: false    # whether or not to store facebook
                                      # generated email addresses
    default_locale: en_US             # the default language to use
    base_perms: ~                     # default permissions to request of facebook
    js_status: true                   # whether to check status of Javascript
    js_xfbml: true                    # whether to parse xfbml in javascript
    profile_class: sfFacebookGraphUserProfile
